# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField(max_length=500)),
                ('sector', models.CharField(max_length=250)),
                ('tech', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('published', models.DateField(null=True)),
            ],
        ),
    ]
