# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='published',
            field=models.DateField(null=True),
        ),
    ]
